### ISSUE TITLE
Move "predict" out of config if possible

### ISSUE THREAD

**Issue by ways** [metno/bris-inference#24]

**Comment by ways** [comment]
Current format:

```
dataloader:
  predict:
    cutout:
      - dataset: ${lam_dataset}
        start: ${start_date}
        end: ${end_date} 
      - dataset: ${global_dataset}
        start: ${start_date}
        end: ${end_date} 
        # rename: 
        #   q_600 : tp  # tp does not exist in the global dataset. tp is diagnostic, rename is sufficient
    min_distance_km: 0
    adjust: all 
```

We agreed on moving _predict_ out of the config file. As discussed in our meeting _lam_dataset_ and _global_dataset_ are names used by our config, but can be called anything else in the config by other users. How can we configure this by default, if we don't necessarily know the variable names?

**Comment by ways** [comment]
Ok, here is the suggestion. 

Format predict like this https://github.com/metno/bris-inference/blob/ccb671c4ec98977427fe6f32168ed12643456030/config/stretched-grid.yaml#L40

And dataset https://github.com/metno/bris-inference/blob/ccb671c4ec98977427fe6f32168ed12643456030/config/stretched-grid.yaml#L15

**Comment by ways** [comment]
So we would end up with:

```
lam_dataset: ${hardware.paths.data}${hardware.files.lam_dataset}
global_dataset: ${hardware.paths.data}${hardware.files.global_dataset}

dataset:
  cutout:
    - dataset: ${lam_dataset}
    - dataset: ${global_dataset}
  min_distance_km: 0
  adjust: all
```

And this hardcoded outside of the config file?

```
dataloader:
  predict:
      dataset: ${dataset}
      start: ${start_date}
      end: ${end_date} 
```

**Comment by havardhhaugen** [comment]
Yes I think that would be the way to go. The only required field in the config would be dataset, and then the user can specify lam_dataset / global_dataset and reference these in dataset if they want to.

**Comment by ways** [comment]
While I'm changing it, could we just drop this part?

```
hardware:
  paths:
    data: /home/larsfp/nobackup/bris/input/
    workdir: /home/larsfp/nobackup/bris/workdir/
  files:
    lam_dataset: meps_2024120306.zarr
    global_dataset: hres_2024120306.zarr
```

Then instead of creating a config variable like lam_dataset, one would use:

```
dataset:
  cutout:
    - dataset: /home/larsfp/nobackup/bris/input/meps_2024120306.zarr
    - dataset: /home/larsfp/nobackup/bris/input/global_dataset: hres_2024120306.zarr
  min_distance_km: 0
  adjust: all
workdir: /home/larsfp/nobackup/bris/tmp
```

**Comment by havardhhaugen** [comment]
Yes, when using ```cutout```the LAM dataset should always be first and the global dataset second (this is decided by anemoi-datasets). And then routing will follow the order specified in the dataset-config.

**Comment by ways** [comment]
We're using dataset at several levels here. Perhaps the outermost should be called datasets ?

> dataset:
>   cutout:
>     - dataset: /home/larsfp/nobackup/bris/input/meps_2024120306.zarr
>     - dataset: /home/larsfp/nobackup/bris/input/hres_2024120306.zarr

**Comment by havardhhaugen** [comment]
I think it's fine the way it is, the usage of dataset further down is tied to kwargs expected by anemoi-datasets. For instance, for a global model with only one input dataset the config would look like this:

```
dataset: PATH_TO_DATASET
```

**Comment by ways** [comment]
> I think it's fine the way it is, the usage of dataset further down is tied to kwargs expected by anemoi-datasets. For instance, for a global model with only one input dataset the config would look like this:
> 
> ```
> dataset: PATH_TO_DATASET
> ```

So you mean both these should be valid?

```
dataset:
  cutout:
    - dataset: /home/larsfp/nobackup/bris/input/meps_2024120306.zarr
    - dataset: /home/larsfp/nobackup/bris/input/hres_2024120306.zarr
```

```
dataset: /home/larsfp/nobackup/bris/input/meps_2024120306.zarr
```

**Comment by havardhhaugen** [comment]
Yes

**Comment by ways** [comment]
```
dataset:
  cutout:
    - dataset: /home/larsfp/nobackup/bris/input/meps_2024120306.zarr
    - dataset: /home/larsfp/nobackup/bris/input/hres_2024120306.zarr
  min_distance_km: 0
  adjust: all
```

Are _min_distance_km_ and _adjust_ valid without cutout? Are they required with cutout, or should there be a default?

**Comment by ways** [comment]
We will have to support lots more options than cutout, so will remove limitations for config.dataset and let anemoi attempt to parse what the user supplies.

**Comment by ways** [comment]
> And this hardcoded outside of the config file
> 
> ```
> dataloader:
>   predict:
>       dataset: ${dataset}
>       start: ${start_date}
>       end: ${end_date} 
> ```

How should this work when cutout is used, @havardhhaugen ? One predict per dataset?

```
dataloader:
  - predict:
      dataset: <dataset1>
      start: ${start_date}
      end: ${end_date} 
  - predict:
      dataset: <dataset2>
      start: ${start_date}
      end: ${end_date} 
```
