### ISSUE TITLE
Simplify keys like "hardware.paths.data"?

### ISSUE THREAD

**Issue by ways** [metno/bris-inference#25]

**Comment by ways** [comment]
Current format:

```
hardware:
  paths:
    data: /home/larsfp/nobackup/bris/input/
    workdir: /home/larsfp/nobackup/bris/workdir/
  files:
    lam_dataset: meps_2024120306.zarr
    global_dataset: hres_2024120306.zarr
```
